services:
  mongodb:
    image: mongo:7.0
    container_name: ${MONGO_CONTAINER_NAME:-nestjs_mongo_db}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-nestjs}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-nestjs}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-nestjs_mongo}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - nestjs_mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME:-nestjs_mongo_express}
    restart: always
    depends_on:
      - mongodb
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-nestjs}:${MONGO_INITDB_ROOT_PASSWORD:-nestjs}@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-mongoexpress}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-mongoexpress}

volumes:
  nestjs_mongo_data:
